# 4.1 사라진 SQLException
- jdbcTemplate을 사용할 시 기존의 코드에 있던 throws SQLException 가 사라진다. SQLException은 JDBC API 메소드들이 던져주는 것이므로 당연히 있어야 하는데 어디로 사라졌는지 알아보도록 한다.
- 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야한다.

## 4.1.2 예외의 종류와 특징
- 체크 예외라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다르는 방식이다. 자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 3가지가 있ㄷ.

### Error
- java.lang.Erro 클래스의 서브 클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생 했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 어플리케이션 코드에서 잡으려고 하면 안된다. OutOfMemoryError나 ThreadDeath 같은 에러는 Catch 블록으로 잡아봤자 아무런 대응 방법이 없다. 
- 따라서 시스템 레벨에서 특별한 작업을 하는게 아니라면 어플리케이션에서는 이런 에에 대한 처리는 신경쓰지않아도 된다.

### Exception과 쳬크 예외

![Image](https://github.com/user-attachments/assets/12a16a23-f311-44bb-b4f2-d92057f8c6e2)

- java.lang.Exception 클래스와 그 서브 클래스로 정의되는 예외들은 에러와 달리 개발자가 만든 어플리케이션 코드의 작업 중에 예외 상황이 발생했을 경우에 사용된다.
- Exception 클래스는 다시 체크 예외와 언체크 예외로 구분된다.
    - 체크 예외 : Exception 클래스의 서브 클래스 이면서 RuntimeException 클래스를 상속하지않는 것들. IDE에서 예외 처리를 강요한다. 예외를 catch로 처리하지않거나 throws로 밖으로 예외를 던지지않을 시 컴파일 에러가 발생한다. 
    - 언체크 예외 : RumtimeException을 상속한 클래스를 말한다.IDE에서 예외 처리를 강제하지않는다. 주로 프로그램의 오류가 있을때 발생하도록 의도된 것들이다. 피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이다.
- 일반적으로 예외라고 하면 Exception 클래스의 서브 클래스 중에서 RumtimeException을 상속하지 않는 것만을 말하는 체크 예외라고 생각해도 된다. 체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야한다.

### RumtimeException과 언체크/런타임 예외
- java.lang.Exception 클래스를 상속한 예외드른 명시적인 예외 처리를 강제 하지않기때문에 언체크 예외라고 불린다. 에러와 마찬가지로 이 런타임예외는 catch문으로 잡거나 throws로 선언하지않아도 된다. 물론 명시적으로 잡거나 throws로 선언해줘도 상관없다. 
- 런타임 예외는 주로 프로그램의 오류가 있을때 발생되도록 의도된 것들이다. 대표적인 예 : NullPointerException, IllegalArgumentException
- 피할 수 있지만 개바라작 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이 런타임 예외이다. 따라서 런타임 예외는 예상하지 못했던 예외 상황에서 발생하는 게 아니기때문에 굳이 catch나 throws를 사용하지않아도 되도록 만든 것이다.

## 4.1.3 예외처리 방법
### 예외 복구
```
int maxRetry = MAX_RETRY;

while(maxRetry --> 0) {
  try {
    ... // 예외가 발생할 수 있는 시도
    return; // 작업 성공
  }
  catch(SomeException e) {
    // 로그 출력, 정해진 시간만큼 대기
  }
  finally {
    // 리소스 반납, 정리 작업
  }
}
throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```
- 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것.예외처리 코드를 강제하는 체크 예외들은 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다.
- 예를 들어, 사용자가 요청한 파일을 읽으려고 시도했는데, 해당 파일이 없거나 다른 문제가 있어서 읽어지지 않는 경우(IOException) 다른 파일을 이용해보라고 안내하면 된다. IOException 에러 메세지가 사용자에게 그냥 던져진다면 예외 복구라고 볼 수 없다. 체크 예외들은 예외가 복구될 가능성이 있는 예외이므로, 예외 복구로 처리되기 위해 사용한다.

### 예외처리 회피 
```
public void add() throws SQLException {
  try {
    // JDBC API
  }
  catch(SQLException e) {
    // 로그 출력
    throw e;
  }
}
```
- 예외 처리를 자신이 담당하지 않고, 자신을 호출한 쪽으로 예외를 던져버리는 방식이다.throws문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것이다.
- 콜백과 템플릿의 관계와 같은 명확한 역할 분담이 없는 상황에서 무작정 예외를 던지면 무책임한 책임회피일 수 있다. 만약 DAO가 SQLException을 던지면, 이 예외는 처리할 곳이 없어서 서비스 레이어로 갔다가 컨트롤러로 가고 결국 그냥 서버로 갈 것이다.
- 예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 콜백/템플릿처럼 긴밀한 다른 오브젝트에게 예외처리 책임을 지게 하거나 자신을 사용하는 쪽에서 예외를 다루는 게 최선이라는 확신이 있어야 한다.

### 예외 전환

```
public void add(User user) throws DuplicateUserIdException, SQLException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
  }
  catch(SQLException e) {
    // ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
    if (e.getERrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw DuplicateUserException();
    else
      throw e; // 그 외의 경우는 SQLException 그대로
  }
}
```
- 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기떄문에 예외를 메소드 밖으로 던지는 것이다. 예외 회피와 달리 발생한 예외를 적절한 예외로 전환해서 던진다는 차이가 있다.
- 예외 전환은 보통 두가지 목적으로 사용된다.
    - 첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외 상황에 대한 적절한 의미를 부여해주지 못하는 경우에 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서다. 예외 전환을 이용하여 SQLException을 DuplicateUserIdException과 같은 예외로 변경하여 던져준다면 예외가 일어난 이유가 한 층 명확해지고 사용자는 다른 아이디를 사용하는 것으로 적절한 복구 작업을 수행할 수 있다. 보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외로 만드는 것이 좋다. 
    - 두번째, 예외를 처리하기 쉽고 단순하게 만들기 위해 포장하는 것이다. 중첩 예외를 이용해 새로운 예외를 만들고 원인이 되는 예외를 내부에 담아서 던지는 방식은 같다. 하지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니라 주로 예외 처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다. 비즈니스적으로 의미도 없고, 복구 가능하지도 않은 예외에 대해서는 런타임 예외(언체크드 예외)로 포장해서 던지는 편이 낫다. 반대로 어플리케이션 로직으로 인한 예외는 체크 예외를 사용하는게 적절하다. 이에 대한 적절한 대응이나 복구전략이 필요하기 때문이다.

```
// 중첩 예외
catch(SQLException e) {
  ...
  throw DuplicateUserIdException(e);
}
// 포장 예외 
try {
  ...
} catch (NamingException ne) {
  throw new EJBException(ne);
} catch (SQLException se) {
  throw new EJBException(se);
} catch (RemoteException re) {
  throw new EJBException(re);
}
```

## 4.1.4 예외 처리 전략
### 런타임 예외의 보편화 
- 일반적으로는 체크 예외가 일반적인 예외를 다루고 언체크 예외는 시스템 장애나 프로그램상의 오류에 사용한다고 했다. 체크 예외는 복구할 가능성이 조금이라도 있는, 말 그대로 예외적인 상황이기 때문에 자바는 이를 처리하는 catch 블록이나 throws 선언을 강제하고 있다.
    - 예외가 발생할 가능성이 있는 API 메소드를 사용하는 개발자의 실수를 방지하기 위한 배려이다.
    - 하지만 실제로는 예외를 제대로 다루고 싶지 않을 만큼 짜증나게 만드는 원인이 되기도 한다.
- 서버 환경은 일반적인 애플리케이션 환경과 다르다. 자바의 환경에 서버로 이동하면서 체크 예외의 활용도와 가치는 점점 떨어지고있다. 
    - 어플리케이션 환경
        - 자바 초기 AWT, 스윙 에서는 파일을 처리한다고 했을 때, 해당 파일이 처리 불가능하면 복구가 필요했다.
        - 워드에서 특정이름의 파일을 검색할 수 없다고 프로그램이 종료되어선 안된다.
    - 서버 환경
        - 한 번에 다수의 사용자가 접근하여 해당 서비스를 이용하기 때문에 작업을 중지하고 예외 상황을 복구할 수 없다!
        - 어플리케이션 차원에서 예외상황을 파악하고 요청에 대한 작업을 취소하는 편이 좋다.

### add() 메소드의 예외처리

```
public class DuplicateUserIdException extends RuntimeException{
    public DuplicateUserIdException(Throwable cause) {
        super(cause);
    }
}

public void add() throws DuplicateUserIdException {
  try {
    // 
  }
  catch (SQLException e) {
    if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw new DuplicateUserIdException(e); // 예외 전환
    else
      throw new RuntimeException(e); // 예외 포장
  }
}
```

- DuplicatedUserIdException도 굳이 체크 예외로 둬야 하는 것은 아니다. DuplicatedUserIdException처럼 의미 있는 예외는 add() 메소드를 바로 호출한 오브젝트 대신 더 앞단의 오브젝트에서 다룰 수도 있다. 어디에서든 DuplicatedUserIdException을 잡아서 처리할 수 있다면 굳이 체크 예외로 만들지 않고 런타임 예외로 만드는 게 낫다.대신 add() 메소드가 DuplicatedUserIdException 을 던진다고 명시적으로 선언해야 한다. 런타임 예외도 throws로 선언 가능하다.
- 이렇게 런타임 예외를 일반화해서 사용하는 방법은 여러모로 장점이 많다. 컴파일러가 예외처리를 강제하지 않으므로 신경쓰지 않으면 예외 상황을 충분히 고려하지 않을 수 있다. 런타임 예외를 사용하는 경우엔 API 문서, 레퍼런스 문서 등을 통해 메소드를 사용할 때 발생할 수 있는 예외의 종류와 원인, 활용 방법을 자세히 설명해둬야한다.

### 어플리케이션 예외
- 런타임 예외 중심 전략은 굳이 이름을 붙이자면 낙관적 예외처리 기법이다. 복구할 수 있는 예외는 없다고 가정한다. 예외가 생겨도 어차피 런타임 예외 이므로 시스템에서 알아서 처리해줄 것이고, 꼭 필요한 경우는 런타임 예외라도 잡아서 복구하거나 대응할 수 있으니 문제될 것이 없다는 낙관적 태도를 기반으로 한다. 혹시 놓치는 예외가 있을까 처리를 강제하는 체크 예외의 비관적인 접근 방법과 대비된다.
- 반면 어플리케이션 예외도 있다. 시스템 혹은 외부 상황이 원인이 아닌 애플리케이션 자체의 로직에 의한 예외이다. 반드시 catch 해서 무엇인가 조치를 취하도록 요구한다.
```
try {
  BigDecimal balance = account.withdraw(amount);
  ...
  // 정상적인 처리 결과를 출력하도록 진행
}
catch(InsufficientBalanceException e) { // 체크 예외
  // InsufficientBalanceException에 담긴 인출 가능한 잔고 금액 정보를 가져옴
  BigDecimal availFunds = e.getAvailFunds();
  ...
  // 잔고 부족 안내 메세지를 준비하고 이를 출력하도록 진행
}
```

## 4.1.5 SQLException은 어떻게 됐나
- 코드 레벨에서 복구 방법이 없는 경우 예외 전환을 통해 언체크 예외를 던져버리는 편이 낫다. 런타임 예외의 보편화와 함께 만일 비즈니스적으로 더 명확한 의미를 줄 수 있는 경우에는 의미를 분명하게 전달할 수 있는 예외를 만들고 중첩 예외로 던져버리는 편이 낫다는 결론을 얻었다. 복구 불가능한 예외를 괜히 체크 예외로 만들면 나쁜 예외처리 습관을 가진 개발자에 의해 더 최악의 시나리오가 발생할 수도 있다.
- SQLException은 복구 불가능하다. 일반적으로 해당 예외가 발생하는 이유는 SQL 문법이 틀렸거나, 제약조건을 위반했거나, DB 서버가 다운됐거나, 네트워크가 불안정하거나, DB 커넥션 풀이 꽉 찬 경우 등이다. 따라서 언체크/런타임 에러로 전환해야 한다.
- 스프링 API 메소드에 정의되어 있는 대부분의 예외는 런타임 예외이다. SQLException이 사라진 이유는 스프링의 JdbcTemplate은 런타임 예외의 보편화 전략을 따르고 있기 때문이다. JdbcTemplate 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다. JdbcTemplate의 update(), queryForInt(), query() 메소드 선언을 잘 살펴보면 모두 throws DataAccessException이라고 되어 있음을 발견할 수 있다.

```
public int update(final String sql) throws DataAccessException {
    //...
}

```
- throws로 선언되어 있긴 하지만 DataAccessException이 런타임 예외이므로 update()를 사용하는 메소드에서 이를 잡거나 다시 던질 이유는 없다.

--- 

참고링크 

https://velog.io/@betterfuture4/Spring-%ED%86%A0%EB%B9%84%EC%9D%98-%EC%8A%A4%ED%94%84%EB%A7%81-4%EC%9E%A5-%EC%98%88%EC%99%B8

https://my-coding-footprints.tistory.com/214

토비의 스프링 3.1 - Vol.1 스프링 이해와 원리